### ISSUE TITLE
All aircraft show as Unknown

### ISSUE THREAD

**Issue by clwgh** [alkissack/Dump1090-OpenLayers3-html#10]
Thanks for this excellent variant of the html. A couple of us used this years ago with the PiAware SD card image v4.0 and it worked great. Trying it now with the PiAware SD card image v8.2 it continues to work well except that the aircraft names always now show as **Unknown**. I've scoured the code but am not sure why the various types defined don't appear. Mentioning it here in case you're not aware and there's a fix. Probably related to some change with how SkyAware works in the current 8.2 version.

![Unknown](https://user-images.githubusercontent.com/115202757/235385496-8515c870-fdd1-4fdb-a5de-23030e6b2c3a.png)

Thanks once again.
Chris

**Comment by clwgh** [comment]
Checking the console showed it was getting 404 trying to access files such as `db/0.json`. Looking in `db` showed these files do not exist – they only have `A`-`F` starting letters, no numbers.

Looking in the original SkyAware 8.2 `db` directory showed these files do exist there, along with many more `A`-`F` files. I renamed your `db` as `db_kissack` and copied over the SkyAware `db` directory to replace it.

I now have most (but not all) types showing. I'm not sure if this represents a valid fix or is just a lucky hack.

![Types](https://user-images.githubusercontent.com/115202757/235407422-43f6ad43-7cff-421e-995d-725886f805eb.png)

**Comment by alkissack** [comment]
Chris
Thanks for flagging this up.  I cannot have a look just now, but when I do
I'll report back.

Al

**Comment by clwgh** [comment]
It looks like it has fixed the database, and the ones which still say **Unknown** are also unknown on the original SkyAware which just shows them as blank. Eg compare theese (note I've also got Registration turned in SkyAware, not sure if I can do that in your view)

![kissack](https://user-images.githubusercontent.com/115202757/235442187-3c78e083-3095-41c8-b127-8653e342ab08.png)

![skyaware](https://user-images.githubusercontent.com/115202757/235442192-9b6ef151-7bd6-4044-86f1-c13e9f7e317a.png)

I appreciate your looking into it as and when you get time. Thanks again. I'm using your version mainly for the overlays and max range plot. It's great!

**Comment by clwgh** [comment]
A bit more info, Al – [most of the database files were deleted in the most recent update](https://github.com/alkissack/Dump1090-OpenLayers3-html/commit/5427d97de874b47e0231e3c48f11e4926523f9ac), perhaps in error? Replacing the database directory with the one from the PiAware image restores many of the entries as a temporary workaround. Your previous database (1200+ entries) actually looks more comprehensive than the [current PiAware one](https://github.com/flightaware/dump1090/commit/ec68bbada7a4b9ef2bebf47cad449339844dc867) (200+ entries) although I might be misinterpreting what I'm seeing here, apologies if so.

**Comment by clwgh** [comment]
I downloaded your previous October release and used the database from it in the current version (instead of using the SkyAware database as a workaround). I now have the military identifiers back plus more detailed civillian types.

Yes it looks like for whatever reason the 7th March update purged a load of database files in error. I don't think any other files outside of `db` are missing. No worries, it's working here with the previous October 2022 database. I'll keep an eye out for another update as and when you have time.

Thanks again,
Chris

**Comment by clwgh** [comment]
I noticed a database refresh a couple of days ago. Does this fix the issue (and presumably updates the `db` to be newer than the previous working Oct 22 commit)? To install it I assume it's just a case of downloading the latest commit and moving the `db` directory to replace the currently installed one?

**Comment by alkissack** [comment]
Hi Chris

I've refreshed the data, but haven't had a chance to do a fresh install
here yet.

If you wish to try, you could rename your db folder and drop in the updated
one.

Allan

**Comment by clwgh** [comment]
With the March 2023 database missing all those files I had been using the March 2023 Master but with the October 2022 database as a drop-in replacement. I've replaced that `db` now with this new May 2023 database and it appears to be working at least as well. Most aircraft types in the table are identified. I assume that a fresh install of `public_html` would give the same result. It looks like the missing database files are back and updated to their newest versions.

Thanks for looking at it. I have a couple of unrelated questions, Allan, relating to some of the parameters in the files such as script.js and config.js (eg relating to range plot altitudes, etc). I want to make sure I'm understanding what I'm seeing in there, not break it, etc. Where is the best place to ask those please?

Thanks,
Chris

**Comment by alkissack** [comment]
I've replaced that db now with this new May 2023 database and it appears to be working - thanks for confrimation
I assume that a fresh install of public_html would give the same result.  -  yes, no core files have been changed recently (only db/)
It looks like the missing database files are back and updated to their newest versions. - yes.  I'll close this

**Comment by alkissack** [comment]
Thanks for looking at it. I have a couple of unrelated questions, Allan, relating to some of the parameters in the files such as script.js and config.js (eg relating to range plot altitudes, etc). I want to make sure I'm understanding what I'm seeing in there, not break it, etc. Where is the best place to ask those please? - Can you email these and I'll reply on that channel and where necessary update the documentation too

**Comment by alkissack** [comment]
db/ folder error.
files now refreshed

**Comment by clwgh** [comment]
> Can you email these and I'll reply on that channel and where necessary update the documentation too

I don't have your email address. Apologies if I'm missing it in here somewhere. As for updates, happy to send PRs too where I can. Thanks, Chris

**Comment by alkissack** [comment]
Chris.
akissack <at> gmail <dot> com

**Comment by alkissack** [comment]
Chris
Feel free to email (akissack at gmail dot com) or open an issue and I'll class it as a question (rather than bug)
ALlan

**Comment by clwgh** [comment]
Thanks, I was going to email tomorrow, but instead I'll open a single issue tomorrow with all the questions in since others may find it useful.
