### ISSUE TITLE
ICAO Type 

### ISSUE THREAD

**Issue by kevdel** [alkissack/Dump1090-OpenLayers3-html#3]
for a selected aircraft the infoblock will show the correct aircraft type. i.e. the span "selected_icaotype" is correct

However, the mouseover on the aircraft icon in the map will show "unknown aircraft" and the name column in the table is empty.

any thoughts on what can be done to get the aircraft type consistent across the 3 areas?

**Comment by alkissack** [comment]
Kev

can you show me an example...
[image: image.png]

Al

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=oa-4885-b>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=oa-4885-b>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by kevdel** [comment]
Here's a screen shot of the issue with 3 red/pink arrows pointing to the areas i referenced above

https://imgur.com/a/v9Lwear

I'm using the latest version dump1090-fa software if that makes any difference

**Comment by kevdel** [comment]
ok.. some digging fixed it

to fix the mousover lack of aircraft type I changed the following
in script.js replace
`                           popname = (Planes[feature.hex].ac_aircraft               ? Planes[feature.hex].ac_aircraft : 'Unknown aircraft type' );`

with 
`	                     popname = (Planes[feature.hex].icaotype               ? Planes[feature.hex].icaotype : 'Unknown aircraft type' );`

to fix the lack of aircraft type in the table I replaced both instances of the following 
`        showColumn(infoTable, "#aircraft_type", !mapIsVisible);`

with
 `       showColumn(infoTable, "#icao_type", !mapIsVisible);`
 
The empty column "Name" in the screenshot above can be removed by commenting out the following 2 lines

` //showColumn(infoTable, "#myAcCat", !mapIsVisible);`
  `//showColumn(infoTable, "#myAcType", !mapIsVisible);`

**Comment by alkissack** [comment]
Thanks.  I'll get that sorted

**Comment by kevdel** [comment]
updated the source and checked and it looks good
