### ISSUE TITLE
Update Request

### ISSUE THREAD

**Issue by finch6** [alkissack/Dump1090-OpenLayers3-html#4]
Hi alkissack,

I wasn't too sure how else to get hold of you. Im fairly new to this.

I love your version of this, especially the aircraft images..!

Any chance you may be working on an updated "list" of aircraft icons/images for the map - to include some Airbus, Embraer images??

Keep up the good work, love it!!!

**Comment by alkissack** [comment]
I am not spending lots of time on teh project, but if you'd like to list the aircraft, I'll see what I can do - Al (flying@kissack.co.uk)

**Comment by gr01d** [comment]
Please add a license, I would like to reuse this project code and try to add playback feature.

**Comment by alkissack** [comment]
done

**Comment by alkissack** [comment]
GPL 2 added
