### ISSUE TITLE
Dump1090-OpenLayers3-html is not compatible with version 8.2 of dump1090-fa

### ISSUE THREAD

**Issue by as365n4** [alkissack/Dump1090-OpenLayers3-html#9]
I set up a test rig with the current FlightAware dump1090-fa and then copied public-html to /usr/share/skyaware and it results only in a blank page with spinning wheel, no map and no planes and no data is being shown.

It worked flawlessly with version 7.2 of dump1090-fa but not with version 8.2, any chance of an update?
Can I support fault finding with logs or anything?

**Comment by as365n4** [comment]
/var/log/lighttpd/error.log

2023-01-15 00:00:01: (server.c.1867) logfiles cycled UID = 0 PID = 589911
2023-01-16 14:43:35: (server.c.2097) server stopped by UID = 0 PID = 1
2023-01-16 14:44:11: (server.c.1588) server started (lighttpd/1.4.67)
2023-01-18 14:35:06: (server.c.2097) server stopped by UID = 0 PID = 1
2023-01-18 14:35:40: (server.c.1588) server started (lighttpd/1.4.67)
2023-01-18 16:28:32: (server.c.2097) server stopped by UID = 0 PID = 1
2023-01-18 16:29:03: (server.c.1588) server started (lighttpd/1.4.67)

**Comment by as365n4** [comment]
/etc/lighttpd/lighttpd.conf

server.modules = (
        "mod_indexfile",
        "mod_access",
        "mod_alias",
        "mod_redirect",
)

server.document-root        = "/var/www/html"
server.upload-dirs          = ( "/var/cache/lighttpd/uploads" )
server.errorlog             = "/var/log/lighttpd/error.log"
server.pid-file             = "/run/lighttpd.pid"
server.username             = "www-data"
server.groupname            = "www-data"
server.port                 = 80

# features
#https://redmine.lighttpd.net/projects/lighttpd/wiki/Server_feature-flagsDetails
server.feature-flags       += ("server.h2proto" => "enable")
server.feature-flags       += ("server.h2c"     => "enable")
server.feature-flags       += ("server.graceful-shutdown-timeout" => 5)
#server.feature-flags       += ("server.graceful-restart-bg" => "enable")

# strict parsing and normalization of URL for consistency and security
# https://redmine.lighttpd.net/projects/lighttpd/wiki/Server_http-parseoptsDetails
# (might need to explicitly set "url-path-2f-decode" = "disable"
#  if a specific application is encoding URLs inside url-path)
server.http-parseopts = (
  "header-strict"           => "enable",# default
  "host-strict"             => "enable",# default
  "host-normalize"          => "enable",# default
  "url-normalize-unreserved"=> "enable",# recommended highly
  "url-normalize-required"  => "enable",# recommended
  "url-ctrls-reject"        => "enable",# recommended
  "url-path-2f-decode"      => "enable",# recommended highly (unless breaks app)
 #"url-path-2f-reject"      => "enable",
  "url-path-dotseg-remove"  => "enable",# recommended highly (unless breaks app)
 #"url-path-dotseg-reject"  => "enable",
 #"url-query-20-plus"       => "enable",# consistency in query string
)

index-file.names            = ( "index.php", "index.html" )
url.access-deny             = ( "~", ".inc" )
static-file.exclude-extensions = ( ".php", ".pl", ".fcgi" )

# default listening port for IPv6 falls back to the IPv4 port
include_shell "/usr/share/lighttpd/use-ipv6.pl " + server.port
include_shell "/usr/share/lighttpd/create-mime.conf.pl"
include "/etc/lighttpd/conf-enabled/*.conf"

#server.compat-module-load   = "disable"
server.modules += (
        "mod_dirlisting",
        "mod_staticfile",
)

**Comment by alkissack** [comment]
I've just installed the latest flightaware (8.2 from https://flightaware.com/adsb/piaware/build/) on a pi. renamed the /usr/share/skyaware/html/ folder, copied in my public_html and renamed it to html (/usr/share/skyaware/html) and found all to be working.  Please ensure you have followed the above in case there is a conflict between the files in the 2 html directories

**Comment by as365n4** [comment]
I am on arm64, so I had to build dump1090-fa myself.
My workflow to install your add-on was as below:

git clone https://github.com/alkissack/Dump1090-OpenLayers3-html.git
cd /usr/share/skyaware
sudo mv html original-html
cd /home/myuser/Dump1090-OpenLayers3-html
sudo cp -R public_html /usr/share/skyaware/html
cd /usr/share/skyaware/html
sudo nano config.js (to set location coordinates)

I will try again and see how it goes.

**Comment by as365n4** [comment]
I've just purged dump1090-fa and skyaware from my machine.
Rebuild the dump1090-fa package and installed it with apt, then rebooted my machine.
Skyaware is showing map and planes, so dump1090-fa is working.
Next removed the html folder from /usr/share/skyaware and then copied public_html to /usr/share/skyaware, renamed it to html and rebooted the machine.
Flushed the browser cache and again I get only the endless spinning wheel and blue stripe running across, but no map no planes and no data, systemctl is reporting that dump1090-fa is running and healthy.
Very strange :-\

**Comment by alkissack** [comment]
If you are using Chrome, can you right click and inspect element, look at console and report any errors

**Comment by as365n4** [comment]
Ok, purge and reinstalled the dump1090-fa package, then replaced html with public_html and renamed to html.
Flushed the browser cache and now I have a map and planes, yay.

Firefox reports the folowing:
![Screenshot from 2023-01-23 19-33-52](https://user-images.githubusercontent.com/69727135/214132702-03fbf285-de72-486d-96b7-ab91d3802549.png)

**Comment by alkissack** [comment]
good news
